### ISSUE TITLE
Fails with Data::Printer 0.99_16+

### ISSUE THREAD

**Issue by andk** [oalders/lwp-consolelogger#13]
As per subject. Fail reports in relation to Data::Printer version:

http://analysis.cpantesters.org/reports_by_field?distv=LWP-ConsoleLogger-0.000038;field=mod%3AData%3A%3APrinter&order=1ta,2nd

**Comment by oalders** [comment]
Thanks @andk! I will look into this.

**Comment by oalders** [comment]
Fixed via 8f5af879fbd724f5ef30582e5959a0897f54fadf

Thanks again @andk.  I had seen a bunch of testers failures but I had no idea where to start looking.  This made it easy.  :)
