### ISSUE TITLE
debug_ua($ua, 0) displays much more than nothing

### ISSUE THREAD

**Issue by jkt628** [oalders/lwp-consolelogger#20]
https://github.com/oalders/lwp-consolelogger/blob/b306d2f00701c286da92e20100cba3c56bd71d3c/lib/LWP/ConsoleLogger/Easy.pm#L166-L167 says

```text
A verbosity of 0 will display nothing.
```

but https://github.com/oalders/lwp-consolelogger/blob/b306d2f00701c286da92e20100cba3c56bd71d3c/lib/LWP/ConsoleLogger/Easy.pm#L26 fails to check for an explicit 0 and turns on all logging.

**Comment by oalders** [comment]
Thanks for reporting @jkt628!
