### ISSUE TITLE
Enable turning debug OFF

### ISSUE THREAD

**Issue by hadjiprocopis** [oalders/lwp-consolelogger#23]
It seems to me that debug_ua() does not turn debug off (set level to 0) once it has been turned on (level > 0). But it remains off when debug_ua($ua, 0).

For example try enabling/disabling the 'first' snippet in the following code:
```
use LWP::UserAgent;
use LWP::ConsoleLogger::Easy qw( debug_ua );

my ($logger, $ua);
# first
print "FIRST TIME\n";
$ua = LWP::UserAgent->new();
$logger = debug_ua( $ua, 10 ); 
$ua->post('localhost:1919191');

print "SECOND TIME\n";
# second, this does not seem to turn debug off
# if 'first' was run. It is off if 'first' was not run
$logger = debug_ua( $ua, 0 );    
$logger->dump_headers( 0 );               
$ua->post('localhost:1919191');
```
It seems  to me that there is no way to turn debug on, then off, then on and then off etc.

Do you think that turning debug ON and OFF repeatedly and at will is a good idea?
By looking at your code, I think it is doable by replacing `$ua->add_handler($phase, $cb)` calls with `$ua->set_my_handler($phase, $cb, owner => 'LWP::ConsoleLogger::Easy')`. Then once a `debug_ua($ua, 0)` is called, remove the installed handlers by `$ua->remove_handler( $phase, owner => 'LWP::ConsoleLogger::Easy');`

If you find this a good idea I can fork and implement this feature

**Comment by oalders** [comment]
I'd probably be more confident if we continued to use `add_handler` and then ensured that `remove_handler` doesn't also remove anything that it shouldn't.

**Comment by hadjiprocopis** [comment]
doing as you suggested (`#$logger = debug_ua( $ua, 0 );`) I don't get 
the headers but I do get
```
POST localhost:1919191

==> 501 Protocol scheme 'localhost' is not supported

.---------------------------------------------------.
| Content                                           |
+---------------------------------------------------+
| 501 Protocol scheme 'localhost' is not supported  |
'---------------------------------------------------'

.---------------------------------------------------.
| Text                                              |
+---------------------------------------------------+
| 501 Protocol scheme 'localhost' is not supported  |
'---------------------------------------------------'
```

I will see where these come from and try to turn them off as well. (I 
suspect they come from the handlers though?)

**Comment by oalders** [comment]
@hadjiprocopis is there anything to address here or should I close the issue?

**Comment by oalders** [comment]
Thanks, @hadjiprocopis!

**Comment by hadjiprocopis** [comment]
Fine, thanks for the insight. I will see where the other route takes me.

(sorry resending this for the list)
