### ISSUE TITLE
default logger settings on LWP::ConsoleLogger::Everywhere import

### ISSUE THREAD

**Issue by mjgardner** [oalders/lwp-consolelogger#24]
I like using `perl -MLWP::ConsoleLogger::Everywhere foo.pl`, but I still have to change code if I want different logger settings. It would be nice if I could set the defaults on import, so I could say `perl '-MLWP::ConsoleLogger::Everywhere (logger => Log::Dispatch->new(outputs => [['File', min_level => 'debug', filename => 'foo.log']]))' foo.pl`.

And for that particular use case, it would be neat if there was a shortcut settings (`log_file`?) that would take care of that `Log::Dispatch` invocation for me, so I could say `perl -MLWP::ConsoleLogger::Everywhere=log_file,foo.log foo.pl`

**Comment by oalders** [comment]
I think this sounds good. I would accept a patch for it. Will also ping @simbabque who originally wrote Everywhere.

**Comment by simbabque** [comment]
Very good idea. Maybe we could even have a dot file?

**Comment by hakonhagland** [comment]
Started on this in #26. Please review!

**Comment by oalders** [comment]
Closed via #28
