### ISSUE TITLE
How to add a test case?

### ISSUE THREAD

**Issue by hakonhagland** [oalders/lwp-consolelogger#30]
I am not able to add a new test in the `t` directory. Maybe something to do with the MANIFEST file? To reproduce from the top directory:

```
$ echo 'print "ok 1";' > t/foo.t
$ dzil build
$ ls LWP-ConsoleLogger-1.000001/t/foo.t
ls: cannot access 'LWP-ConsoleLogger-1.000001/t/foo.t': No such file or directory
```

**Comment by oalders** [comment]
If you `git add` new files, they should show up in the build. I think otherwise, they won't be included. (Not intuitive).

**Comment by hakonhagland** [comment]
> If you git add new files, they should show up in the build.

Yes that worked, but not easy to discover :)
