### ISSUE TITLE
v5.21.6-93-g2917948 breaks 0.000019

### ISSUE THREAD

**Issue by andk** [oalders/lwp-consolelogger#4]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/6b30476c-0650-11e5-8601-24aaf292232d

There may be other relevant changes between v5.21.6-93-g2917948 and v5.22. This is just my attempt to provide the result of a bisect run. All perls after v5.21.6-93-g2917948 are failing too, as can be seen in the matrix:

http://matrix.cpantesters.org/?dist=LWP-ConsoleLogger+0.000019

**Comment by oalders** [comment]
Thanks very much for raising this issue.  I dug a bit deeper and it looks like this has been fixed via 752c7a076  :)

http://matrix.cpantesters.org/?dist=LWP-ConsoleLogger%200.000020;perl=5.22.0;reports=1
