### ISSUE TITLE
something is missing an encode somewhere

### ISSUE THREAD

**Issue by rjbs** [oalders/lwp-consolelogger#6]
Here's my program:

```perl
use strict;
use LWP::ConsoleLogger::Easy qw( debug_ua );
use LWP::UserAgent;
my $mech           = LWP::UserAgent->new;
my $console_logger = debug_ua( $mech );
$mech->get( 'http://rjbs.manxome.org/tmp/unicode.html' );
```

I'll leave that URL there, but it contains:

```html
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  </head>
  <body>
    😄
  </body>
</html>
```

Note the literal non-ASCII character.

When printing the content, I get this to my STDERR:

> Wide character in print at /Users/rjbs/.plenv/versions/24.0/lib/perl5/site_perl/5.24.0/Log/Dispatch/Screen.pm line 51.

It sounds like something is getting decoded content, building a table, but never encoding the output.

**Comment by rjbs** [comment]
Come see my talk at YAPC, [A Million Billion Squiggly Characters](http://www.yapcna.org/yn2016/talk/6630), all about this problem! &amp;#x1F604;

**Comment by oalders** [comment]
If only I were going to be at YAPC, this year.  I will try to catch the video.  :)

I was actually discussing this with @autarch earlier this week, but didn't have a failing case to show him, so this is helpful.

We talked about the wacky LWP behaviour around decoding.  That's nicely documented here: https://github.com/kentnl/HTTP-Tiny-Mech/pull/2

It seems the easy fix is to pass `utf8 => 1` to `Log::Dispatch::Screen` when the object is created.  Does that seem correct(ish) to you?

**Comment by oalders** [comment]
Not sure why Travis failed this on everything but 5.22 https://travis-ci.org/oalders/lwp-consolelogger/builds/138519723

**Comment by oalders** [comment]
Had to bump the Log::Dispatch version.  Builds are fixed now.

**Comment by oalders** [comment]
Unicode handling improved version now on CPAN.
